import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ExternalLink, FileSearch, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { sourcesApi } from '@/features/grounding/api/sourcesApi'
import type { SourceReference } from '@/features/grounding/types/source'
import { useLanguage } from '@/i18n/LanguageProvider'

type SourceTarget={type:'flashcard'|'question'|'job';id:string}
const focusable='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'

export function SourceViewer({target,sources:initialSources,compact=false}:{target?:SourceTarget;sources?:SourceReference[];compact?:boolean}){
  const[open,setOpen]=useState(false);const{language}=useLanguage();const vi=language==='vi';const triggerRef=useRef<HTMLButtonElement>(null);const dialogRef=useRef<HTMLElement>(null)
  const query=useQuery({queryKey:['sources',target?.type,target?.id],queryFn:()=>target!.type==='flashcard'?sourcesApi.flashcard(target!.id):target!.type==='question'?sourcesApi.question(target!.id):sourcesApi.job(target!.id),enabled:open&&Boolean(target)&&initialSources===undefined})
  const sources=initialSources??query.data;const label=vi?'Xem nguồn':'View source'
  function close(){setOpen(false);requestAnimationFrame(()=>triggerRef.current?.focus())}
  useEffect(()=>{if(!open)return;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';requestAnimationFrame(()=>dialogRef.current?.querySelector<HTMLElement>(focusable)?.focus());function keydown(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab'||!dialogRef.current)return;const items=Array.from(dialogRef.current.querySelectorAll<HTMLElement>(focusable));if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}document.addEventListener('keydown',keydown);return()=>{document.removeEventListener('keydown',keydown);document.body.style.overflow=previousOverflow}},[open])
  return <><button ref={triggerRef} type="button" onClick={()=>setOpen(true)} className={compact?'inline-flex min-h-10 items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700':'inline-flex min-h-11 items-center gap-2 rounded-xl border border-indigo-200 bg-white px-4 py-2 text-sm font-semibold text-indigo-700'}><FileSearch aria-hidden size={16}/>{label}</button>
    {open&&<div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/40 p-0 sm:place-items-center sm:p-6" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="source-viewer-title" className="max-h-[85dvh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] shadow-2xl sm:max-w-2xl sm:rounded-3xl sm:p-6"><header className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold text-indigo-600">{vi?'Dẫn chứng':'Grounding evidence'}</p><h2 id="source-viewer-title" className="mt-1 text-xl font-semibold text-slate-950">{label}</h2></div><button type="button" onClick={close} aria-label={vi?'Đóng nguồn':'Close sources'} className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-700"><X aria-hidden size={20}/></button></header>
      <div aria-live="polite">{query.isPending&&!initialSources&&<div className="mt-6 space-y-3" aria-label={vi?'Đang tải nguồn':'Loading sources'}><div className="skeleton h-28 rounded-2xl"/><div className="skeleton h-28 rounded-2xl"/></div>}{query.isError&&<p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{vi?'Không thể tải nguồn. Hãy đóng và thử lại.':"Sources couldn't be loaded. Close this panel and try again."}</p>}{sources?.length===0&&<p className="mt-6 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">{vi?'Nội dung này chưa có nguồn tài liệu.':'This content has no document source.'}</p>}</div>
      <div className="mt-5 space-y-4">{sources?.map(source=><article key={source.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-slate-900">{source.documentName}</strong><span className={`rounded-lg px-2.5 py-1 text-xs font-semibold ${source.documentAvailable?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{source.documentAvailable?(vi?'Còn tài liệu':'Available'):(vi?'Chỉ còn bản lưu':'Saved snapshot')}</span></div><p className="mt-2 text-xs text-slate-500">{[source.pageNumber?`${vi?'Trang':'Page'} ${source.pageNumber}`:null,source.slideNumber?`Slide ${source.slideNumber}`:null,source.sectionTitle].filter(Boolean).join(' · ')||`${vi?'Vị trí':'Offsets'} ${source.startOffset}–${source.endOffset}`}</p><blockquote className="mt-3 whitespace-pre-wrap border-l-2 border-indigo-300 pl-3 text-sm leading-6 text-slate-600">{source.snippet}</blockquote>{source.documentAvailable&&source.documentId&&<Link to={`/documents/${source.documentId}?${source.pageNumber?`page=${source.pageNumber}`:source.slideNumber?`slide=${source.slideNumber}`:source.documentChunkId?`chunk=${source.documentChunkId}`:''}&start=${source.startOffset}&end=${source.endOffset}`} onClick={close} className="mt-3 inline-flex min-h-11 items-center gap-2 py-2 text-sm font-semibold text-indigo-700">{vi?'Mở đúng vị trí':'Open source location'}<ExternalLink aria-hidden size={15}/></Link>}{!source.documentAvailable&&<p className="mt-3 text-xs text-slate-500">{vi?'Tài liệu gốc đã bị xóa. Đoạn trích được giữ để bảo toàn lịch sử.':'The original document was deleted. This saved excerpt preserves the citation history.'}</p>}</article>)}</div>
    </section></div>}
  </>
}
