import { useEffect, useEffectEvent, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { RatingButtons } from '@/features/progress/components/RatingButtons'
import { reviewKeys, reviewsApi } from '@/features/progress/api/reviewsApi'
import { studySessionsApi } from '@/features/studySessions/api/studySessionsApi'
import type { DueFlashcard, ReviewRating } from '@/features/progress/types/progress'
import { useLanguage } from '@/i18n/LanguageProvider'
import { PronunciationControls } from '@/features/flashcards/components/PronunciationControls'
import { LearningSessionShell, SessionHeader, SessionProgress, SessionSummary } from '@/features/learning/components/LearningSessionShell'

export function DueReviewPage() {
  const [readingRevealed, setReadingRevealed] = useState(false); const [revealed, setRevealed] = useState(false); const [initialTotal,setInitialTotal]=useState(0); const activeSession = useRef<{ id: string; studySetId: string } | null>(null); const queryClient = useQueryClient(); const navigate = useNavigate(); const { t, language } = useLanguage(); const vi = language === 'vi'
  const due = useQuery({ queryKey: reviewKeys.due, queryFn: reviewsApi.due })
  const review = useMutation({ mutationFn: async ({ card, rating }: { card: DueFlashcard; rating: ReviewRating }) => { if (activeSession.current?.studySetId !== card.studySetId) { if (activeSession.current) await studySessionsApi.complete(activeSession.current.id); const started = await studySessionsApi.start(card.studySetId, 'Review'); activeSession.current = { id: started.id, studySetId: card.studySetId } } return reviewsApi.review(card.flashcardId, rating, activeSession.current.id) }, onSuccess: async (_, input) => { setInitialTotal(current=>current||due.data?.length||0);const remaining = due.data?.filter((card) => card.flashcardId !== input.card.flashcardId) ?? []; queryClient.setQueryData<DueFlashcard[]>(reviewKeys.due, remaining); setReadingRevealed(false); setRevealed(false); if (remaining.length === 0 && activeSession.current) { await studySessionsApi.complete(activeSession.current.id); activeSession.current = null; queryClient.invalidateQueries({ queryKey: ['dashboard'] }) } } })
  const card = due.data?.[0]
  const rateFromKeyboard = useEffectEvent((rating: ReviewRating) => { if (card) review.mutate({ card, rating }) })
  useEffect(() => { function keydown(event: KeyboardEvent) { if (!card || review.isPending) return; if (event.code === 'Space') { event.preventDefault(); if (card.languageCode && card.readingText && !readingRevealed && !revealed) setReadingRevealed(true); else setRevealed((value) => !value); return } const ratings: Record<string, ReviewRating> = { '1': 'Again', '2': 'Hard', '3': 'Good', '4': 'Easy' }; if (revealed && ratings[event.key]) rateFromKeyboard(ratings[event.key]) } window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown) }, [card, readingRevealed, revealed, review.isPending])
  async function exitReview() { if (activeSession.current) await studySessionsApi.complete(activeSession.current.id); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); navigate('/home') }
  if (due.isPending) return <main className="grid min-h-screen place-items-center text-slate-500">{t('loading')}</main>
  if (due.isError) return <main className="grid min-h-screen place-items-center text-red-700">{vi ? 'Không thể tải thẻ cần ôn.' : 'Unable to load due cards.'}</main>
  if (!card) return <SessionSummary eyebrow={t('allCaught')} title={t('noDue')} primaryAction={<Link to="/home" className="sf-primary rounded-xl px-5 py-3 font-bold text-white">{t('returnHome')}</Link>}/>
  const hasReadingStep = Boolean(card.languageCode && card.readingText)
  const advance = () => { if (hasReadingStep && !readingRevealed && !revealed) setReadingRevealed(true); else setRevealed((value) => !value) }
  const sessionTotal=initialTotal||due.data?.length||0;const completed=sessionTotal-(due.data?.length??0)
  return <LearningSessionShell><SessionHeader exitLabel={t('exitReview')} onExit={()=>void exitReview()} current={completed+1} total={sessionTotal}/><div className="mt-4"><SessionProgress current={completed+1} total={sessionTotal}/></div><div className="mt-6 flex justify-between"><span className="text-sm font-bold text-[#111943]">{t('review')}</span><span className="metric-number text-sm text-slate-500">{due.data?.length} {t('due')}</span></div><section className="sf-card mt-5 flex min-h-[24rem] w-full flex-col items-center justify-center rounded-[2rem] p-9 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${revealed ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'}`}>{revealed ? t('answer') : t('question')}</span><span className="mt-7 whitespace-pre-wrap text-2xl font-bold leading-10 text-[#111943] sm:text-3xl">{revealed ? card.backText : card.frontText}</span>{!revealed && readingRevealed && <span className="mt-4 text-xl font-semibold text-blue-700">{card.readingText}</span>}{!revealed && readingRevealed && card.romanization && <span className="mt-2 text-sm text-slate-500">{card.romanization}</span>}{card.languageCode && <span className="mt-6"><PronunciationControls text={card.readingText || card.frontText} languageCode={card.languageCode} /></span>}{revealed && card.explanation && <span className="mt-8 border-t border-slate-100 pt-6 text-slate-500">{card.explanation}</span>}</section><div className="mt-5">{revealed ? <RatingButtons pending={review.isPending} onRate={(rating) => review.mutate({ card, rating })} /> : <button onClick={advance} className="sf-primary w-full rounded-xl px-6 py-3 font-bold text-white">{hasReadingStep && !readingRevealed ? (vi ? 'Hiện cách đọc' : 'Show reading') : t('showAnswer')}</button>}</div><p className="mt-4 text-center text-xs text-slate-400">{vi ? 'Phím tắt: Space để tiếp tục · 1–4 để đánh giá' : 'Shortcuts: Space to continue · 1–4 to rate'}</p>{review.isError && <p role="alert" className="mt-4 text-center text-sm text-red-600">{vi ? 'Không thể lưu kết quả. Hãy thử lại trước khi tiếp tục.' : 'Could not save this review. Try again before continuing.'}</p>}</LearningSessionShell>
}
