using System.Text;
using System.Text.Json;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using StudyFlow.Application.AI.DTOs;
using StudyFlow.Application.AI.Interfaces;
using StudyFlow.Application.Common.Models;
using StudyFlow.Application.Grounding;
using StudyFlow.Domain.Entities;
using StudyFlow.Domain.Enums;
using StudyFlow.Infrastructure.AI;

namespace StudyFlow.Infrastructure.Persistence.Services;

internal sealed class AIWorkflowService(StudyFlowDbContext db,IAIService ai,IValidator<SaveAIDraftRequest> draftValidator,IDocumentContextRetriever retriever,IGroundingValidator groundingValidator,TimeProvider clock):IAIWorkflowService
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web);
    public async Task<Result<IReadOnlyList<AIJobDto>>> GenerateAsync(Guid userId,Guid studySetId,GenerateStudyMaterialRequest request,CancellationToken token)
    {
        if(!await OwnsSet(userId,studySetId,token))return Result<IReadOnlyList<AIJobDto>>.Failure("STUDY_SET_NOT_FOUND","Study set was not found.",ErrorType.NotFound);
        DocumentContextResult? grounding=null;string material;
        if(request.DocumentId.HasValue){var retrieved=await retriever.RetrieveAsync(userId,[request.DocumentId.Value],$"{request.Difficulty} key concepts definitions examples",null,token);if(!retrieved.IsSuccess)return Result<IReadOnlyList<AIJobDto>>.Failure(retrieved.Error!.Code,retrieved.Error.Message,retrieved.Error.Type);grounding=retrieved.Value!;material=BuildMaterial(grounding);}
        else material=request.PastedText!.Trim();
        var context=new AIGenerationContext(material,request.Difficulty,request.DocumentOnly,grounding is not null);var jobs=new List<AIJobDto>();
        if(request.GenerateFlashcards)jobs.Add(await RunDraftJob(userId,studySetId,request.DocumentId,AIJobType.GenerateFlashcards,grounding,async()=>new AIDraftDto((await ai.GenerateFlashcardsAsync(context,request.FlashcardCount,token)).Flashcards,[]),request.FlashcardCount,token));
        if(request.GenerateQuiz)jobs.Add(await RunDraftJob(userId,studySetId,request.DocumentId,AIJobType.GenerateQuiz,grounding,async()=>new AIDraftDto([],(await ai.GenerateQuizAsync(context,request.QuizQuestionCount,token)).Questions),request.QuizQuestionCount,token));
        return Result<IReadOnlyList<AIJobDto>>.Success(jobs);
    }
    public async Task<Result<AIJobDto>> GetJobAsync(Guid userId,Guid jobId,CancellationToken token){var job=await db.AIJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==jobId&&x.UserId==userId,token);return job is null?Result<AIJobDto>.Failure("AI_JOB_NOT_FOUND","AI job was not found.",ErrorType.NotFound):Result<AIJobDto>.Success(ToDto(job));}
    public async Task<Result<SavedAIDraftDto>> SaveDraftAsync(Guid userId,Guid jobId,SaveAIDraftRequest request,CancellationToken token)
    {
        var job=await db.AIJobs.SingleOrDefaultAsync(x=>x.Id==jobId&&x.UserId==userId,token);if(job is null)return Result<SavedAIDraftDto>.Failure("AI_JOB_NOT_FOUND","AI job was not found.",ErrorType.NotFound);if(job.Status!=AIJobStatus.Completed)return Result<SavedAIDraftDto>.Failure("AI_JOB_NOT_COMPLETED","Only completed AI drafts can be saved.",ErrorType.Conflict);if(job.SavedAt.HasValue)return Result<SavedAIDraftDto>.Failure("AI_DRAFT_ALREADY_SAVED","AI draft was already saved.",ErrorType.Conflict);
        var validation=await draftValidator.ValidateAsync(request,token);if(!validation.IsValid)return Result<SavedAIDraftDto>.Failure("INVALID_AI_DRAFT",validation.Errors[0].ErrorMessage,ErrorType.Validation);var original=JsonSerializer.Deserialize<AIDraftDto>(job.ResultJson!,JsonOptions)!;
        if(job.JobType==AIJobType.GenerateFlashcards&&(request.Flashcards.Count==0||request.Questions.Count>0)||job.JobType==AIJobType.GenerateQuiz&&(request.Questions.Count==0||request.Flashcards.Count>0))return Result<SavedAIDraftDto>.Failure("AI_DRAFT_TYPE_MISMATCH","The submitted draft does not match the AI job type.",ErrorType.Validation);
        if(request.Flashcards.Count!=original.Flashcards.Count||request.Questions.Count!=original.Questions.Count)return Result<SavedAIDraftDto>.Failure("AI_DRAFT_STRUCTURE_CHANGED","Draft items cannot be added or removed before saving.",ErrorType.Validation);
        if(request.Flashcards.Count>0&&await db.StudySets.AnyAsync(x=>x.Id==job.StudySetId&&x.Type==StudySetType.Combined,token))return Result<SavedAIDraftDto>.Failure("COMBINED_SET_READ_ONLY","Save generated flashcards to a source study set.",ErrorType.Conflict);
        var context=ReadContext(job);var sourceSets=new List<IReadOnlyList<ValidatedSource>>();if(context is not null){foreach(var ids in original.Flashcards.Select(x=>x.SourceIds??[]).Concat(original.Questions.Select(x=>x.SourceIds??[]))){var grounded=await groundingValidator.ValidateAsync(userId,ids,context,token);if(grounded.Valid.Count==0)return Result<SavedAIDraftDto>.Failure("GROUNDING_SOURCE_INVALID","A draft source changed or is no longer available.",ErrorType.Conflict);sourceSets.Add(grounded.Valid);}}
        await using var transaction=db.Database.ProviderName?.Contains("Npgsql",StringComparison.Ordinal)==true?await db.Database.BeginTransactionAsync(token):null;var sourceIndex=0;var cardsCreated=0;Guid? quizId=null;
        if(request.Flashcards.Count>0){var next=(await db.Flashcards.Where(x=>x.StudySetId==job.StudySetId).MaxAsync(x=>(int?)x.OrderIndex,token)??-1)+1;foreach(var pair in request.Flashcards.Select((value,index)=>(value,index))){var x=pair.value;var card=Flashcard.Create(job.StudySetId,x.FrontText,x.BackText,x.Explanation,next+pair.index,x.LanguageCode,x.ReadingText,x.Romanization,x.ExampleText,x.ExampleTranslation,x.MemoryTip,x.AcceptedAnswers);db.Flashcards.Add(card);if(context is not null)AddReferences(GroundedContentType.Flashcard,card.Id,sourceSets[sourceIndex++],context.RetrievalRevision);}cardsCreated=request.Flashcards.Count;}
        if(request.Questions.Count>0){var quiz=Quiz.Create(job.StudySetId,request.QuizTitle,request.Questions.Count);db.Quizzes.Add(quiz);quizId=quiz.Id;foreach(var pair in request.Questions.Select((value,index)=>(value,index))){var x=pair.value;var type=x.Type=="TrueFalse"?QuestionType.TrueFalse:QuestionType.MultipleChoice;var question=Question.CreateGenerated(quiz.Id,type,x.QuestionText,x.Explanation,pair.index);db.Questions.Add(question);db.AnswerOptions.AddRange(x.Options.Select((option,index)=>AnswerOption.Create(question.Id,option.Text,option.IsCorrect,index)));if(context is not null)AddReferences(GroundedContentType.QuizQuestion,question.Id,sourceSets[sourceIndex++],context.RetrievalRevision);}}
        job.MarkSaved(clock.GetUtcNow());await db.SaveChangesAsync(token);if(transaction is not null)await transaction.CommitAsync(token);return Result<SavedAIDraftDto>.Success(new(cardsCreated,quizId,request.Questions.Count));
    }
    public Task<Result<AITextResultDto>> ExplainAsync(Guid userId,Guid cardId,CancellationToken token)=>RunTextJob(userId,cardId,AIJobType.Explain,GroundedContentType.Explanation,(m,c)=>ai.ExplainAsync(m,c.FrontText,c.BackText,token),token);
    public Task<Result<AITextResultDto>> SimilarQuestionAsync(Guid userId,Guid cardId,CancellationToken token)=>RunTextJob(userId,cardId,AIJobType.GenerateSimilarQuestion,GroundedContentType.SimilarQuestion,(m,c)=>ai.GenerateSimilarQuestionAsync(m,c.FrontText,c.BackText,token),token);
    public Task<Result<AITextResultDto>> HintAsync(Guid userId,Guid cardId,int level,CancellationToken token)=>RunTextJob(userId,cardId,AIJobType.TutorHint,GroundedContentType.TutorHint,(m,c)=>ai.GenerateHintAsync(m,c.FrontText,level,token),token);
    private async Task<Result<AITextResultDto>> RunTextJob(Guid userId,Guid cardId,AIJobType jobType,GroundedContentType contentType,Func<string,Flashcard,Task<GroundedTextProviderResult>> action,CancellationToken token)
    {
        var card=await db.Flashcards.SingleOrDefaultAsync(x=>x.Id==cardId&&db.StudySets.Any(s=>s.Id==x.StudySetId&&db.Subjects.Any(u=>u.Id==s.SubjectId&&u.UserId==userId)),token);if(card is null)return Result<AITextResultDto>.Failure("FLASHCARD_NOT_FOUND","Flashcard was not found.",ErrorType.NotFound);
        var documentIds=await db.SourceReferences.Where(x=>x.ContentType==GroundedContentType.Flashcard&&x.ContentId==cardId&&x.DocumentId!=null).Select(x=>x.DocumentId!.Value).Distinct().Take(5).ToListAsync(token);if(documentIds.Count==0)documentIds=await db.Documents.Where(x=>x.UserId==userId&&x.StudySetId==card.StudySetId&&x.ProcessingStatus==DocumentProcessingStatus.Ready).OrderByDescending(x=>x.CreatedAt).Select(x=>x.Id).Take(5).ToListAsync(token);if(documentIds.Count==0)return Result<AITextResultDto>.Failure("AI_SOURCE_REQUIRED","Import a ready document into this study set first.",ErrorType.Validation);
        var retrieved=await retriever.RetrieveAsync(userId,documentIds,$"{card.FrontText} {card.BackText}",null,token);if(!retrieved.IsSuccess)return Result<AITextResultDto>.Failure(retrieved.Error!.Code,retrieved.Error.Message,retrieved.Error.Type);var context=retrieved.Value!;var job=AIJob.Create(userId,card.StudySetId,documentIds[0],jobType);job.SetGroundingContext(JsonSerializer.Serialize(context,JsonOptions),context.RetrievalRevision);db.AIJobs.Add(job);await db.SaveChangesAsync(token);job.Start(clock.GetUtcNow());await db.SaveChangesAsync(token);
        try{var output=await action(BuildMaterial(context),card);var grounded=await groundingValidator.ValidateAsync(userId,output.SourceIds??[],context,token);if(grounded.Valid.Count==0)throw new GroundingException("GROUNDING_REQUIRED_SOURCE_MISSING");job.Complete(JsonSerializer.Serialize(output,JsonOptions),clock.GetUtcNow());var references=AddReferences(contentType,job.Id,grounded.Valid,context.RetrievalRevision);await db.SaveChangesAsync(token);return Result<AITextResultDto>.Success(new(job.Id,output.Answer,references.Zip(grounded.Valid,(reference,source)=>ToDto(reference.Id,source)).ToList()));}catch(Exception ex)when(ex is not OperationCanceledException){job.Fail(ex is GroundingException?"AI grounding failed.":SafeError(ex),clock.GetUtcNow());await db.SaveChangesAsync(token);return Result<AITextResultDto>.Failure(ex is GroundingException?"AI_GROUNDING_FAILED":"AI_GENERATION_FAILED",job.ErrorMessage!,ErrorType.Validation);}
    }
    private async Task<AIJobDto> RunDraftJob(Guid userId,Guid setId,Guid? documentId,AIJobType type,DocumentContextResult? context,Func<Task<AIDraftDto>> action,int requested,CancellationToken token)
    {
        var job=AIJob.Create(userId,setId,documentId,type);if(context is not null)job.SetGroundingContext(JsonSerializer.Serialize(context,JsonOptions),context.RetrievalRevision);db.AIJobs.Add(job);await db.SaveChangesAsync(token);job.Start(clock.GetUtcNow());await db.SaveChangesAsync(token);
        try{var draft=await action();if(context is not null){var cards=new List<GeneratedFlashcardDto>();foreach(var item in draft.Flashcards){var valid=await groundingValidator.ValidateAsync(userId,item.SourceIds??[],context,token);if(valid.Valid.Count>0)cards.Add(item with{SourceIds=AliasesFor(valid.Valid,context)});}var questions=new List<GeneratedQuestionDto>();foreach(var item in draft.Questions){var valid=await groundingValidator.ValidateAsync(userId,item.SourceIds??[],context,token);if(valid.Valid.Count>0)questions.Add(item with{SourceIds=AliasesFor(valid.Valid,context)});}draft=new(cards,questions);if(cards.Count+questions.Count==0)throw new GroundingException("AI_GROUNDING_FAILED");}var actual=type==AIJobType.GenerateFlashcards?draft.Flashcards.Count:draft.Questions.Count;if(actual==0||actual>requested)throw new ValidationException("AI returned an invalid number of items.");var validation=await draftValidator.ValidateAsync(new SaveAIDraftRequest(draft.Flashcards,draft.Questions),token);if(!validation.IsValid)throw new ValidationException(validation.Errors);job.Complete(JsonSerializer.Serialize(draft,JsonOptions),clock.GetUtcNow());}catch(Exception ex)when(ex is not OperationCanceledException){job.Fail(ex is GroundingException?"AI grounding failed.":SafeError(ex),clock.GetUtcNow());}await db.SaveChangesAsync(token);return ToDto(job);
    }
    private IReadOnlyList<SourceReference> AddReferences(GroundedContentType type,Guid contentId,IReadOnlyList<ValidatedSource> sources,string revision){var references=sources.Select(x=>SourceReference.Create(x.DocumentId,x.DocumentChunkId,type,contentId,x.PageNumber,x.SlideNumber,x.SectionTitle,x.StartOffset,x.EndOffset,x.ContentHash,revision,x.DocumentName,x.Snippet)).ToList();db.SourceReferences.AddRange(references);return references;}
    private static IReadOnlyList<string> AliasesFor(IReadOnlyList<ValidatedSource> sources,DocumentContextResult context){var ids=sources.Select(x=>x.DocumentChunkId).ToHashSet();return context.Chunks.Where(x=>ids.Contains(x.DocumentChunkId)).Select(x=>x.Alias).ToList();}
    private static string BuildMaterial(DocumentContextResult context){var result=new StringBuilder();foreach(var chunk in context.Chunks){result.Append("SOURCE ").Append(chunk.Alias).Append("\nDocument: ").Append(chunk.DocumentName);if(chunk.PageNumber.HasValue)result.Append("\nPage: ").Append(chunk.PageNumber);if(chunk.SlideNumber.HasValue)result.Append("\nSlide: ").Append(chunk.SlideNumber);if(chunk.SectionTitle is not null)result.Append("\nSection: ").Append(chunk.SectionTitle);result.Append("\n\n").Append(chunk.Content).Append("\n\n");}return result.ToString();}
    private static DocumentContextResult? ReadContext(AIJob job)=>job.GroundingContextJson is null?null:JsonSerializer.Deserialize<DocumentContextResult>(job.GroundingContextJson,JsonOptions);
    private Task<bool> OwnsSet(Guid userId,Guid setId,CancellationToken token)=>db.StudySets.AnyAsync(x=>x.Id==setId&&db.Subjects.Any(s=>s.Id==x.SubjectId&&s.UserId==userId),token);
    private static string SafeError(Exception ex)=>ex switch{AIProviderException=>ex.Message,InvalidOperationException when ex.Message.Contains("API key")=>"Gemini API key is not configured.",_=>"AI generation failed. Please retry."};
    private static AIJobDto ToDto(AIJob job){AIDraftDto? draft=null;if(job.Status==AIJobStatus.Completed&&job.ResultJson is not null)draft=JsonSerializer.Deserialize<AIDraftDto>(job.ResultJson,JsonOptions);return new(job.Id,job.StudySetId,job.DocumentId,job.JobType,job.Status,job.ErrorMessage,draft,job.CreatedAt,job.CompletedAt,job.SavedAt);}
    private static SourceReferenceDto ToDto(Guid id,ValidatedSource x)=>new(id,x.DocumentId,x.DocumentName,x.DocumentChunkId,x.PageNumber,x.SlideNumber,x.SectionTitle,x.Snippet,x.StartOffset,x.EndOffset,true);
    private sealed class GroundingException(string code):Exception(code);
}
