import { useQuery } from '@tanstack/react-query'
import { ArrowRight, BookOpen, Clock3, FileUp, Flame, Play, RotateCcw, Sparkles, Target } from 'lucide-react'
import type { ReactNode } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { authApi } from '@/features/auth/api/authApi'
import { useAuthStore } from '@/features/auth/store/authStore'
import { dashboardApi, dashboardKeys } from '@/features/dashboard/api/dashboardApi'
import { subjectKeys, subjectsApi } from '@/features/subjects/api/subjectsApi'
import { useLanguage } from '@/i18n/LanguageProvider'
import { ErrorState, PageSkeleton } from '@/components/ui/FeedbackState'

function formatDuration(seconds:number,locale:string){if(seconds<60)return locale==='vi'?`${seconds} giây`:`${seconds}s`;const minutes=Math.floor(seconds/60);return minutes<60?`${minutes} min`:`${Math.floor(minutes/60)}h ${minutes%60}m`}
function relativeTime(value:string,locale:string){const minutes=Math.max(1,Math.round((Date.now()-new Date(value).getTime())/60000));if(minutes<60)return locale==='vi'?`${minutes} phút trước`:`${minutes}m ago`;const hours=Math.round(minutes/60);return locale==='vi'?`${hours} giờ trước`:`${hours}h ago`}

export function HomePage(){
  const user=useAuthStore(state=>state.user);const clearSession=useAuthStore(state=>state.clearSession);const navigate=useNavigate();const{language}=useLanguage();const vi=language==='vi'
  const dashboard=useQuery({queryKey:dashboardKeys.all,queryFn:dashboardApi.get});const subjects=useQuery({queryKey:subjectKeys.all,queryFn:subjectsApi.list})
  async function logout(){try{await authApi.logout()}finally{clearSession();navigate('/login',{replace:true})}}
  if(dashboard.isPending||subjects.isPending)return <PageSkeleton/>
  if(dashboard.isError||subjects.isError)return <main className="mx-auto max-w-6xl px-5 py-12"><ErrorState title={vi?'Không thể tải trang chủ':'Home could not be loaded'} description={vi?'Kiểm tra kết nối rồi thử lại.':'Check your connection and try again.'} retryLabel={vi?'Thử lại':'Try again'} onRetry={()=>{void dashboard.refetch();void subjects.refetch()}}/></main>
  const value=dashboard.data
  if(subjects.data.length===0)return <main className="mx-auto max-w-5xl px-5 pb-10 pt-6"><header className="flex items-center justify-between"><span className="brand-mark">Study<span>Flow</span></span><button onClick={logout} className="text-sm font-semibold text-slate-500">{vi?'Đăng xuất':'Sign out'}</button></header><section className="mt-12 max-w-2xl"><p className="text-sm font-semibold text-blue-600">{vi?`Chào ${user?.displayName}`:`Welcome, ${user?.displayName}`}</p><h1 className="mt-3 text-4xl font-semibold leading-tight tracking-[-.045em] text-slate-950 sm:text-6xl">{vi?'Bắt đầu buổi học đầu tiên.':'Build your first study session.'}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-500">{vi?'Thêm tài liệu để StudyFlow tạo nội dung có nguồn, hoặc tự tạo môn học và flashcard.':'Upload notes for source-backed AI generation, or create your subjects and cards manually.'}</p></section><section className="mt-10 grid gap-4 md:grid-cols-[1.15fr_.85fr]"><Link to="/documents" className="group rounded-3xl bg-[#1b3478] p-7 text-white shadow-[0_22px_50px_rgba(28,52,120,.2)]"><FileUp size={28}/><h2 className="mt-12 text-2xl font-semibold">{vi?'Tải ghi chú lên':'Upload my notes'}</h2><p className="mt-2 max-w-md text-sm leading-6 text-blue-100">PDF, DOCX, PPTX, TXT · {vi?'Tạo flashcard và quiz sau khi xử lý xong.':'Generate flashcards and quizzes when processing is ready.'}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold">{vi?'Bắt đầu':'Get started'} <ArrowRight className="transition-transform group-hover:translate-x-1" size={18}/></span></Link><Link to="/subjects" className="group rounded-3xl bg-white p-7 shadow-[0_16px_44px_rgba(38,56,112,.08)]"><BookOpen className="text-blue-600" size={28}/><h2 className="mt-12 text-2xl font-semibold text-slate-950">{vi?'Tạo thủ công':'Create manually'}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{vi?'Tạo môn học, bộ học và nhập những flashcard đầu tiên.':'Create a subject, a study set, and your first flashcards.'}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-blue-700">{vi?'Tạo môn học':'Create a subject'} <ArrowRight className="transition-transform group-hover:translate-x-1" size={18}/></span></Link></section></main>
  const estimated=Math.max(5,Math.ceil(value.dueCards*.65));const recent=value.recentStudySets[0]
  return <main className="mx-auto max-w-6xl px-5 pb-10 pt-5"><section className="relative overflow-hidden rounded-[2rem] bg-[#1b3478] p-6 text-white shadow-[0_24px_55px_rgba(32,55,124,.22)] sm:p-9"><div className="relative z-10 max-w-2xl"><p className="text-sm font-medium text-blue-100">{vi?'Hôm nay':"Today's study"} · {user?.displayName}</p><h1 className="mt-3 text-3xl font-semibold leading-tight tracking-[-.045em] sm:text-5xl">{value.dueCards?(vi?'Củng cố những gì sắp quên.':'Strengthen what is starting to fade.'):(vi?'Bạn đã theo kịp lịch ôn.':'You are caught up for now.')}</h1><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-blue-100"><span className="inline-flex items-center gap-2"><RotateCcw size={17}/>{value.dueCards} {vi?'thẻ đến hạn':'due cards'}</span><span className="inline-flex items-center gap-2"><Clock3 size={17}/>{vi?'Khoảng':'About'} {estimated} min</span></div><Link to="/study/today" className="mt-8 inline-flex min-h-12 items-center gap-3 rounded-xl bg-white px-6 py-3 font-semibold text-[#1b3478] shadow-lg shadow-blue-950/20"><Play size={18} fill="currentColor"/>{vi?'Bắt đầu học':'Start learning'}<ArrowRight size={18}/></Link></div><Sparkles className="absolute -bottom-8 -right-5 text-white/10" size={210} strokeWidth={.7}/></section>
    {recent&&<section className="mt-8"><p className="text-sm font-semibold text-slate-500">{vi?'Tiếp tục học':'Continue learning'}</p><Link to={`/study-sets/${recent.id}`} className="group mt-3 flex items-center gap-4 rounded-2xl bg-white p-5 shadow-[0_10px_34px_rgba(38,56,112,.07)]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700"><BookOpen size={21}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-slate-950">{recent.title}</strong><small className="mt-1 block text-slate-500">{vi?'Học lần cuối':'Last studied'} {relativeTime(recent.lastStudiedAt,language)}</small></span><ArrowRight className="text-blue-600 transition-transform group-hover:translate-x-1 group-hover:text-blue-600" size={20}/></Link></section>}
    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-blue-600">{vi?'Tiến độ':'Progress'}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{vi?'Nhịp học hôm nay':'Today at a glance'}</h2></div><Link to="/progress" className="text-sm font-semibold text-blue-700">{vi?'Xem chi tiết':'View details'} →</Link></div><div className="mt-4 grid grid-cols-3 gap-3"><Metric icon={<Clock3 size={18}/>} label={vi?'Thời gian':'Study time'} value={formatDuration(value.studyTimeSecondsToday,language)}/><Metric icon={<Target size={18}/>} label={vi?'Độ chính xác':'Accuracy'} value={`${value.accuracyToday}%`}/><Metric icon={<Flame size={18}/>} label={vi?'Đã ôn':'Reviewed'} value={value.cardsReviewedToday}/></div></section>
    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-blue-600">{vi?'Thư viện':'Library'}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{vi?'Môn học của bạn':'Your subjects'}</h2></div><Link to="/subjects" className="text-sm font-semibold text-blue-700">{vi?'Xem tất cả':'See all'} →</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{subjects.data.slice(0,4).map(subject=><Link key={subject.id} to={`/subjects/${subject.id}`} className="group flex min-h-24 items-center gap-4 rounded-2xl bg-white p-5 shadow-[0_10px_34px_rgba(38,56,112,.06)]"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-700"><BookOpen size={19}/></span><strong className="min-w-0 flex-1 truncate text-slate-950">{subject.name}</strong><ArrowRight className="text-slate-400 transition-transform group-hover:translate-x-1 group-hover:text-blue-600" size={18}/></Link>)}</div></section>
  </main>
}

function Metric({icon,label,value}:{icon:ReactNode;label:string;value:ReactNode}){return <article className="rounded-2xl bg-white p-4 shadow-[0_10px_34px_rgba(38,56,112,.06)]"><span className="text-blue-600">{icon}</span><p className="mt-3 text-xs text-slate-500">{label}</p><strong className="metric-number mt-1 block text-lg text-slate-950">{value}</strong></article>}
