import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { SubjectForm } from '@/features/subjects/components/SubjectForm'
import { subjectKeys, subjectsApi } from '@/features/subjects/api/subjectsApi'
import { useLanguage } from '@/i18n/LanguageProvider'

const themes = ['bg-blue-50 text-blue-600', 'bg-rose-50 text-rose-600', 'bg-violet-50 text-violet-600', 'bg-emerald-50 text-emerald-600']
export function SubjectsPage() {
  const [creating, setCreating] = useState(false); const queryClient = useQueryClient(); const { t } = useLanguage()
  const subjects = useQuery({ queryKey: subjectKeys.all, queryFn: subjectsApi.list }); const createSubject = useMutation({ mutationFn: subjectsApi.create, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: subjectKeys.all }); setCreating(false) } })
  return <main className="mx-auto max-w-6xl px-5 pb-8 pt-6"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold text-blue-600">{t('library')}</p><h1 className="mt-1 text-4xl font-bold tracking-[-.04em] text-[#111943]">{t('mySubjects')}</h1><p className="mt-2 text-slate-500">{t('subjectsCopy')}</p></div><button onClick={() => setCreating(true)} className="sf-primary rounded-xl px-5 py-3 text-sm font-bold text-white">＋ {t('createSubject')}</button></header>{creating && <section className="sf-card mt-7 rounded-[1.7rem] p-6"><h2 className="mb-5 text-xl font-bold">{t('createSubject')}</h2><SubjectForm pending={createSubject.isPending} submitLabel={t('createSubject')} onCancel={() => setCreating(false)} onSubmit={input => createSubject.mutateAsync(input).then(() => undefined)} /></section>}<section className="mt-8">{subjects.isPending && <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{[1,2,3,4].map(item => <div key={item} className="h-44 animate-pulse rounded-3xl bg-white/70" />)}</div>}{subjects.isError && <p role="alert" className="rounded-2xl bg-red-50 p-5 text-red-700">Unable to load subjects.</p>}{subjects.data?.length === 0 && !creating && <div className="sf-card rounded-3xl px-6 py-16 text-center"><span className="text-4xl text-blue-500">＋</span><h2 className="mt-4 text-xl font-bold">{t('noSubjects')}</h2><p className="mt-2 text-slate-500">{t('noSubjectsCopy')}</p></div>}<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{subjects.data?.map((subject,index) => <Link key={subject.id} to={`/subjects/${subject.id}`} className="sf-card group min-h-44 rounded-[1.6rem] p-5 transition duration-200 hover:-translate-y-1"><div className={`grid h-12 w-12 place-items-center rounded-2xl text-xl font-black ${themes[index % themes.length]}`}>{subject.name.charAt(0).toUpperCase()}</div><h2 className="mt-5 truncate text-lg font-bold text-[#111943] group-hover:text-blue-600">{subject.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-5 text-slate-500">{subject.description ?? t('noDescription')}</p></Link>)}</div></section></main>
}
