// oxlint-disable react/only-export-components -- provider and hook intentionally share one context
import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react'

export type Language = 'en' | 'vi'
const messages = {
  en: {
    home: 'Home', subjects: 'Subjects', review: 'Review', progress: 'Progress', documents: 'Documents', greeting: 'Good to see you', momentum: 'Small steps build lasting knowledge.', due: 'cards due', dueCopy: 'Ready to strengthen your memory?', startReview: 'Start review', studyTime: 'Study time', accuracy: 'Accuracy', streak: 'Streak', today: 'today', days: 'days', yourSubjects: 'Your subjects', seeAll: 'See all', recentSets: 'Continue learning', library: 'Library', noRecent: 'Complete a review or quiz and your recent sets will appear here.', insights: 'Progress & insights', importDocs: 'Import documents', signOut: 'Sign out', mySubjects: 'My subjects', subjectsCopy: 'Organize your learning, your way.', createSubject: 'New subject', loadingSubjects: 'Loading subjects…', noSubjects: 'No subjects yet', noSubjectsCopy: 'Create your first subject to start organizing your learning.', noDescription: 'No description yet.', studySets: 'Study sets', createStudySet: 'New study set', collections: 'Collections of material within this subject.', allSubjects: 'All subjects', editSubject: 'Edit subject', loading: 'Loading…', question: 'Question', answer: 'Answer', showAnswer: 'Reveal answer', previous: 'Previous', exitStudy: 'Exit study', preparing: 'Preparing cards…', unableOpen: 'Unable to open this study set.', noCards: 'No flashcards yet', addCards: 'Add flashcards', allCaught: 'All caught up', noDue: 'No cards are due.', returnHome: 'Return home', exitReview: 'Exit review', weakCards: 'Weak cards', flashcardStatus: 'Flashcard status', totalCards: 'Total cards', cardsReviewed: 'Cards reviewed', quizAccuracy: 'Quiz accuracy', recommended: 'Recommended review', learningStory: 'See what you know—and what needs work.', progressInsights: 'Progress & insights', studyStreak: 'Study streak', activeDays: 'active days', sessions: 'sessions', studied: 'studied', upload: 'Upload & extract', importDocument: 'Import a document', language: 'Language', again: 'Again', hard: 'Hard', good: 'Good', easy: 'Easy', next: 'Next', cancel: 'Cancel', save: 'Save', edit: 'Edit', delete: 'Delete', close: 'Close', retry: 'Try again', quiz: 'Quiz', quizzes: 'Quizzes', startQuiz: 'Start quiz', submitQuiz: 'Submit quiz', correct: 'correct', wrong: 'wrong', answered: 'answered', backLibrary: 'Back to library', quizComplete: 'Quiz complete', wrongReview: 'Wrong-answer review', yourAnswer: 'Your answer', correctAnswer: 'Correct answer', noAnswer: 'No answer',
  },
  vi: {
    home: 'Trang chủ', subjects: 'Môn học', review: 'Ôn tập', progress: 'Tiến độ', documents: 'Tài liệu', greeting: 'Rất vui gặp lại bạn', momentum: 'Mỗi bước nhỏ tạo nên kiến thức bền vững.', due: 'thẻ cần ôn', dueCopy: 'Sẵn sàng củng cố trí nhớ?', startReview: 'Bắt đầu ôn', studyTime: 'Thời gian học', accuracy: 'Độ chính xác', streak: 'Chuỗi ngày', today: 'hôm nay', days: 'ngày', yourSubjects: 'Môn học của bạn', seeAll: 'Xem tất cả', recentSets: 'Tiếp tục học', library: 'Thư viện', noRecent: 'Hoàn thành một lượt ôn hoặc bài trắc nghiệm để xem bộ học gần đây.', insights: 'Tiến độ và phân tích', importDocs: 'Nhập tài liệu', signOut: 'Đăng xuất', mySubjects: 'Môn học của tôi', subjectsCopy: 'Sắp xếp việc học theo cách của bạn.', createSubject: 'Thêm môn học', loadingSubjects: 'Đang tải môn học…', noSubjects: 'Chưa có môn học', noSubjectsCopy: 'Tạo môn học đầu tiên để bắt đầu sắp xếp kiến thức.', noDescription: 'Chưa có mô tả.', studySets: 'Bộ học', createStudySet: 'Thêm bộ học', collections: 'Các nhóm nội dung thuộc môn học này.', allSubjects: 'Tất cả môn học', editSubject: 'Sửa môn học', loading: 'Đang tải…', question: 'Câu hỏi', answer: 'Đáp án', showAnswer: 'Xem đáp án', previous: 'Trước', exitStudy: 'Thoát buổi học', preparing: 'Đang chuẩn bị thẻ…', unableOpen: 'Không thể mở bộ học này.', noCards: 'Chưa có flashcard', addCards: 'Thêm flashcard', allCaught: 'Đã hoàn thành', noDue: 'Không còn thẻ cần ôn.', returnHome: 'Về trang chủ', exitReview: 'Thoát ôn tập', weakCards: 'Thẻ cần cải thiện', flashcardStatus: 'Trạng thái flashcard', totalCards: 'Tổng số thẻ', cardsReviewed: 'Thẻ đã ôn', quizAccuracy: 'Độ chính xác trắc nghiệm', recommended: 'Đề xuất ôn tập', learningStory: 'Biết rõ điều bạn đã nhớ và phần cần cải thiện.', progressInsights: 'Tiến độ và phân tích', studyStreak: 'Chuỗi ngày học', activeDays: 'ngày hoạt động', sessions: 'buổi học', studied: 'đã học', upload: 'Tải lên và trích xuất', importDocument: 'Nhập tài liệu', language: 'Ngôn ngữ', again: 'Học lại', hard: 'Khó', good: 'Tốt', easy: 'Dễ', next: 'Tiếp theo', cancel: 'Hủy', save: 'Lưu', edit: 'Sửa', delete: 'Xóa', close: 'Đóng', retry: 'Thử lại', quiz: 'Trắc nghiệm', quizzes: 'Bài trắc nghiệm', startQuiz: 'Bắt đầu làm bài', submitQuiz: 'Nộp bài', correct: 'đúng', wrong: 'sai', answered: 'đã trả lời', backLibrary: 'Về thư viện', quizComplete: 'Hoàn thành bài', wrongReview: 'Xem lại câu trả lời sai', yourAnswer: 'Bạn đã chọn', correctAnswer: 'Đáp án đúng', noAnswer: 'Chưa trả lời',
  },
} as const

export type MessageKey = keyof typeof messages.en
const LanguageContext = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: MessageKey) => string } | null>(null)

export function LanguageProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<Language>(() => localStorage.getItem('studyflow-language') === 'vi' ? 'vi' : 'en')
  useEffect(() => { document.documentElement.lang = language }, [language])
  const value = useMemo(() => ({ language, setLanguage: (next: Language) => { localStorage.setItem('studyflow-language', next); setLanguageState(next) }, t: (key: MessageKey) => messages[language][key] }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('LanguageProvider is missing.'); return value }
