import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, ArrowLeft, CheckCircle2, Clock3, FileText, RefreshCw, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DocumentUploader } from '@/features/documents/components/DocumentUploader'
import { documentKeys, documentsApi } from '@/features/documents/api/documentsApi'
import type { DocumentProcessingStatus } from '@/features/documents/types/document'
import { EmptyState, ErrorState } from '@/components/ui/FeedbackState'
import { useLanguage } from '@/i18n/LanguageProvider'

function size(bytes:number){return bytes<1024*1024?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`}

export function DocumentsPage(){
  const queryClient=useQueryClient();const{language}=useLanguage();const vi=language==='vi'
  const documents=useQuery({queryKey:documentKeys.all,queryFn:documentsApi.list,refetchInterval:query=>query.state.data?.some(item=>item.processingStatus==='Uploaded'||item.processingStatus==='Queued'||item.processingStatus==='Processing')?3000:false})
  const remove=useMutation({mutationFn:documentsApi.remove,onSuccess:()=>queryClient.invalidateQueries({queryKey:documentKeys.all})});const retry=useMutation({mutationFn:documentsApi.retry,onSuccess:()=>queryClient.invalidateQueries({queryKey:documentKeys.all})})
  const statusText:Record<DocumentProcessingStatus,string>={Uploaded:vi?'Đã tải lên':'Uploaded',Queued:vi?'Đang chờ xử lý':'Waiting to process',Processing:vi?'Đang đọc tài liệu':'Reading document',Ready:vi?'Sẵn sàng cho AI':'Ready for AI',Failed:vi?'Xử lý thất bại':'Processing failed'}
  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-6 sm:py-10"><Link to="/home" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-700"><ArrowLeft size={17}/>{vi?'Trang chủ':'Home'}</Link><header className="mt-6"><p className="text-sm font-semibold text-indigo-600">{vi?'Nguồn học tập':'Study sources'}</p><h1 className="mt-2 max-w-3xl text-4xl font-semibold tracking-tight text-slate-950">{vi?'Biến ghi chú thành nội dung có thể học.':'Turn your notes into study material.'}</h1><p className="mt-3 max-w-2xl leading-7 text-slate-500">{vi?'Tải file lên rồi tiếp tục công việc khác. StudyFlow sẽ báo khi tài liệu sẵn sàng tạo flashcard và quiz.':'Upload a file and continue with something else. StudyFlow will show when it is ready for flashcards and quizzes.'}</p></header><div className="mt-8"><DocumentUploader/></div>
    <section className="mt-8 rounded-3xl bg-white p-5 shadow-[0_16px_44px_rgba(38,56,112,.07)] sm:p-7"><h2 className="text-xl font-semibold">{vi?'Tài liệu của bạn':'Your documents'}</h2>{documents.isPending&&<div className="mt-6 space-y-3" aria-live="polite"><div className="skeleton h-16 rounded-xl"/><div className="skeleton h-16 rounded-xl"/></div>}{documents.isError&&<div className="mt-6"><ErrorState title={vi?'Không thể tải tài liệu':'Documents could not be loaded'} description={vi?'Kiểm tra kết nối rồi thử lại.':'Check your connection and try again.'} retryLabel={vi?'Thử lại':'Try again'} onRetry={()=>void documents.refetch()}/></div>}{documents.data?.length===0&&<div className="mt-6"><EmptyState icon={<FileText size={23}/>} title={vi?'Chưa có tài liệu':'No documents yet'} description={vi?'Tải ghi chú đầu tiên để tạo nội dung học có thể kiểm chứng nguồn.':'Upload your first notes to create source-backed study material.'}/></div>}
      <ul className="mt-4 divide-y divide-slate-100">{documents.data?.map(document=>{const active=document.processingStatus==='Uploaded'||document.processingStatus==='Queued'||document.processingStatus==='Processing';const StatusIcon=document.processingStatus==='Ready'?CheckCircle2:document.processingStatus==='Failed'?AlertCircle:Clock3;return <li key={document.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="flex min-w-0 items-start gap-3"><span className={`mt-0.5 grid h-10 w-10 shrink-0 place-items-center rounded-xl ${document.processingStatus==='Ready'?'bg-emerald-50 text-emerald-700':document.processingStatus==='Failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}><StatusIcon className={active?'animate-pulse':''} size={18}/></span><div className="min-w-0"><Link to={`/documents/${document.id}`} className="block truncate font-semibold text-slate-950 hover:text-indigo-600">{document.originalFileName}</Link><p className="mt-1 text-sm text-slate-500">{document.fileType} · {size(document.fileSize)} · <span className={document.processingStatus==='Failed'?'text-red-700':document.processingStatus==='Ready'?'text-emerald-700':'text-amber-700'}>{statusText[document.processingStatus]}</span></p></div></div><div className="flex gap-2">{document.canRetry&&<button disabled={retry.isPending} onClick={()=>retry.mutate(document.id)} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-semibold text-indigo-700"><RefreshCw size={16}/>{vi?'Thử lại':'Retry'}</button>}<button aria-label={vi?`Xóa ${document.originalFileName}`:`Delete ${document.originalFileName}`} disabled={remove.isPending||document.processingStatus==='Processing'} onClick={()=>window.confirm(vi?'Xóa tài liệu và file đã lưu?':'Delete this document and its stored file?')&&remove.mutate(document.id)} className="grid h-11 w-11 place-items-center rounded-xl text-red-700 hover:bg-red-50 disabled:opacity-40"><Trash2 size={17}/></button></div></li>})}</ul>
    </section>
  </main>
}
