import { useEffect, useRef } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertCircle, ArrowLeft, CheckCircle2, Clock3, FileText, RefreshCw, Sparkles } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { documentKeys, documentsApi } from '@/features/documents/api/documentsApi'
import { ErrorState, PageSkeleton } from '@/components/ui/FeedbackState'
import { useLanguage } from '@/i18n/LanguageProvider'

export function DocumentDetailPage(){
  const{id=''}=useParams();const[params]=useSearchParams();const queryClient=useQueryClient();const{language}=useLanguage();const vi=language==='vi';const highlightRef=useRef<HTMLElement>(null)
  const document=useQuery({queryKey:documentKeys.detail(id),queryFn:()=>documentsApi.get(id),enabled:Boolean(id),refetchInterval:query=>{const status=query.state.data?.processingStatus;return status==='Uploaded'||status==='Queued'||status==='Processing'?2500:false}})
  const retry=useMutation({mutationFn:()=>documentsApi.retry(id),onSuccess:value=>{queryClient.setQueryData(documentKeys.detail(id),value);queryClient.invalidateQueries({queryKey:documentKeys.all})}})
  useEffect(()=>{if(document.data?.processingStatus==='Ready'&&highlightRef.current)requestAnimationFrame(()=>highlightRef.current?.scrollIntoView({behavior:'smooth',block:'center'}))},[document.data?.processingStatus])
  if(document.isPending)return <PageSkeleton/>
  if(document.isError)return <main className="mx-auto max-w-5xl px-6 py-12"><ErrorState title={vi?'Không tìm thấy tài liệu':'Document not found'} description={vi?'Tài liệu có thể đã bị xóa hoặc bạn không có quyền truy cập.':'The document may have been deleted or is not available to your account.'}/></main>
  const item=document.data;const active=item.processingStatus==='Uploaded'||item.processingStatus==='Queued'||item.processingStatus==='Processing';const text=item.extractedText??'';const start=Number(params.get('start'));const end=Number(params.get('end'));const canHighlight=Number.isInteger(start)&&Number.isInteger(end)&&start>=0&&end>start&&end<=text.length;const location=[params.get('page')?`${vi?'Trang':'Page'} ${params.get('page')}`:null,params.get('slide')?`Slide ${params.get('slide')}`:null,params.get('chunk')?vi?'Đoạn nguồn':'Source chunk':null].filter(Boolean).join(' · ')
  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-8 sm:px-6 sm:py-10"><Link to="/documents" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-700"><ArrowLeft aria-hidden size={17}/>{vi?'Tài liệu':'Documents'}</Link><header className="mt-6"><div className="flex items-center gap-2 text-sm font-semibold text-indigo-600"><FileText size={17}/><span>{item.fileType} · {statusLabel(item.processingStatus,vi)}</span></div><h1 className="mt-3 break-words text-3xl font-semibold tracking-tight text-slate-950">{item.originalFileName}</h1><p className="mt-2 text-sm text-slate-500">{item.chunkCount} {vi?'đoạn đã xử lý':'processed chunks'} · {vi?'Thử lại':'Retries'} {item.retryCount}</p></header>
    {active&&<section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6" aria-live="polite"><div className="flex items-center gap-3"><Clock3 className="animate-pulse text-amber-700" size={21}/><h2 className="font-semibold text-amber-950">{item.processingStatus==='Processing'?(vi?'Đang đọc và chuẩn bị tài liệu':'Reading and preparing your document'):(vi?'Đang chờ xử lý':'Waiting to be processed')}</h2></div><p className="mt-2 text-sm leading-6 text-amber-800">{vi?'Trang này tự cập nhật. Bạn có thể rời đi và quay lại sau.':'This page updates automatically. You can safely leave and return later.'}</p></section>}
    {item.processingStatus==='Failed'&&<section className="mt-8 rounded-2xl bg-red-50 p-5 text-red-800" role="alert"><div className="flex gap-3"><AlertCircle className="shrink-0" size={22}/><div><h2 className="font-semibold">{vi?'Không thể xử lý tài liệu':'We could not process this document'}</h2><p className="mt-2 text-sm">{vi?'Kiểm tra định dạng file rồi thử lại.':'Check the file format, then try again.'}</p>{item.canRetry&&<button disabled={retry.isPending} onClick={()=>retry.mutate()} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-red-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><RefreshCw size={16}/>{retry.isPending?(vi?'Đang xếp hàng…':'Queueing…'):(vi?'Thử lại':'Try again')}</button>}</div></div></section>}
    {item.processingStatus==='Ready'&&<><section className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-emerald-50 p-5"><div className="flex items-center gap-3"><CheckCircle2 className="text-emerald-700" size={22}/><div><h2 className="font-semibold text-emerald-950">{vi?'Sẵn sàng tạo nội dung học':'Ready for AI study material'}</h2><p className="mt-1 text-sm text-emerald-800">{vi?'Tài liệu đã được đọc và chia thành các đoạn có thể truy nguồn.':'The document is processed into source-backed chunks.'}</p></div></div>{item.studySetId&&<Link to={`/study-sets/${item.studySetId}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white"><Sparkles size={16}/>{vi?'Tạo nội dung':'Generate material'}</Link>}</section>
      <section className="mt-6 rounded-3xl bg-white p-5 shadow-[0_16px_44px_rgba(38,56,112,.07)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-lg font-semibold text-slate-950">{vi?'Nội dung đã trích xuất':'Extracted document text'}</h2><p className="mt-1 text-sm text-slate-500">{location||(vi?'Toàn bộ tài liệu':'Full document')}</p></div>{canHighlight&&<span className="rounded-lg bg-amber-100 px-3 py-1.5 text-xs font-semibold text-amber-900">{vi?'Đã đánh dấu nguồn':'Source highlighted'}</span>}</div><pre className="mt-5 max-h-[65dvh] overflow-auto whitespace-pre-wrap break-words rounded-2xl bg-slate-50 p-4 font-sans text-sm leading-7 text-slate-700 sm:p-6">{canHighlight?<>{text.slice(0,start)}<mark ref={highlightRef} className="scroll-m-24 rounded bg-amber-200 px-1 text-slate-950 ring-4 ring-amber-100">{text.slice(start,end)}</mark>{text.slice(end)}</>:text||(vi?'Không tìm thấy văn bản có thể đọc trong tài liệu này.':'No readable text was found in this document.')}</pre></section></>}
  </main>
}
function statusLabel(status:string,vi:boolean){const labels:Record<string,[string,string]>={Uploaded:['Đã tải lên','Uploaded'],Queued:['Đang chờ','Queued'],Processing:['Đang xử lý','Processing'],Ready:['Sẵn sàng','Ready'],Failed:['Xử lý thất bại','Processing failed']};return labels[status]?.[vi?0:1]??status}
