import { useState, type FormEvent } from 'react'
import { useMutation } from '@tanstack/react-query'
import type { Flashcard, FlashcardInput } from '@/features/flashcards/types/flashcard'
import { aiApi } from '@/features/ai/api/aiApi'
import { useLanguage } from '@/i18n/LanguageProvider'
import { PronunciationControls } from '@/features/flashcards/components/PronunciationControls'
import { FlashcardImage } from '@/features/flashcards/components/FlashcardImage'
import type { AITextResult } from '@/features/ai/types/ai'
import { SourceViewer } from '@/features/grounding/components/SourceViewer'

export function FlashcardListItem({card,pending,onUpdate,onDelete,onUploadImage,onDeleteImage}:{card:Flashcard;pending:boolean;onUpdate:(input:FlashcardInput)=>Promise<void>;onDelete:()=>void;onUploadImage:(file:File)=>Promise<void>;onDeleteImage:()=>Promise<void>}) {
  const { language } = useLanguage(); const vi = language === 'vi'; const [editing,setEditing] = useState(false); const [aiResult,setAiResult] = useState<AITextResult|null>(null)
  const copy = vi ? {front:'MẶT TRƯỚC',back:'MẶT SAU',explanation:'Giải thích (không bắt buộc)',cancel:'Hủy',save:'Lưu',edit:'Sửa',delete:'Xóa',image:'Thêm hình ảnh',replaceImage:'Đổi ảnh',removeImage:'Xóa ảnh',explain:'Giải thích bằng AI',similar:'Câu hỏi tương tự',working:'Gemini đang xử lý…',reverse:'Ôn đảo chiều'} : {front:'FRONT',back:'BACK',explanation:'Explanation (optional)',cancel:'Cancel',save:'Save',edit:'Edit',delete:'Delete',image:'Add image',replaceImage:'Replace image',removeImage:'Remove image',explain:'AI explanation',similar:'Similar question',working:'Gemini is working…',reverse:'Reverse recall'}
  const explain = useMutation({mutationFn:()=>aiApi.explain(card.id),onSuccess:setAiResult}); const similar = useMutation({mutationFn:()=>aiApi.similar(card.id),onSuccess:setAiResult})
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); await onUpdate({frontText:String(data.get('frontText')).trim(),backText:String(data.get('backText')).trim(),explanation:String(data.get('explanation')).trim()||null,languageCode:String(data.get('languageCode')).trim()||null,readingText:String(data.get('readingText')).trim()||null,romanization:String(data.get('romanization')).trim()||null,exampleText:String(data.get('exampleText')).trim()||null,exampleTranslation:String(data.get('exampleTranslation')).trim()||null,memoryTip:String(data.get('memoryTip')).trim()||null,acceptedAnswers:String(data.get('acceptedAnswers')).trim()||null,enableReverseRecall:data.get('enableReverseRecall')==='on'}); setEditing(false) }
  if (editing) return <form onSubmit={submit} className="sf-card rounded-2xl p-5">
    <div className="grid gap-4 sm:grid-cols-2"><textarea required name="frontText" defaultValue={card.frontText} maxLength={1000} rows={3} className="rounded-xl border border-slate-200 p-3"/><textarea required name="backText" defaultValue={card.backText} maxLength={5000} rows={3} className="rounded-xl border border-slate-200 p-3"/></div>
    <textarea name="explanation" defaultValue={card.explanation??''} maxLength={5000} rows={2} placeholder={copy.explanation} className="mt-3 w-full rounded-xl border border-slate-200 p-3"/>
    <div className="mt-3 grid gap-3 rounded-xl bg-blue-50 p-3 sm:grid-cols-3"><input name="languageCode" defaultValue={card.languageCode??''} maxLength={35} placeholder="Language: ja-JP" className="rounded-lg border border-blue-100 p-2"/><input name="readingText" defaultValue={card.readingText??''} maxLength={500} placeholder="Reading" className="rounded-lg border border-blue-100 p-2"/><input name="romanization" defaultValue={card.romanization??''} maxLength={500} placeholder="Romanization" className="rounded-lg border border-blue-100 p-2"/></div>
    <div className="mt-3 grid gap-3 rounded-xl bg-amber-50 p-3 sm:grid-cols-2"><textarea name="exampleText" defaultValue={card.exampleText??''} maxLength={2000} rows={2} placeholder="Example sentence" className="rounded-lg border border-amber-100 p-2"/><textarea name="exampleTranslation" defaultValue={card.exampleTranslation??''} maxLength={2000} rows={2} placeholder="Example translation" className="rounded-lg border border-amber-100 p-2"/><textarea name="memoryTip" defaultValue={card.memoryTip??''} maxLength={2000} rows={2} placeholder="Memory tip" className="rounded-lg border border-amber-100 p-2"/><textarea name="acceptedAnswers" defaultValue={card.acceptedAnswers??''} maxLength={2000} rows={2} placeholder="Accepted answers, one per line" className="rounded-lg border border-amber-100 p-2"/><label className="flex items-center gap-2 text-sm font-semibold text-amber-900"><input name="enableReverseRecall" type="checkbox" defaultChecked={card.enableReverseRecall}/>{copy.reverse}</label></div>
    <div className="mt-3 flex justify-end gap-2"><button type="button" onClick={()=>setEditing(false)} className="px-3 py-2 text-sm">{copy.cancel}</button><button disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">{copy.save}</button></div>
  </form>
  const aiPending=explain.isPending||similar.isPending; const aiError=explain.error||similar.error
  return <article className="sf-card rounded-2xl p-5"><div className="grid gap-4 sm:grid-cols-[3rem_1fr_1fr_auto]"><span className="text-sm font-bold text-slate-400">{card.orderIndex+1}</span><div><p className="text-xs font-bold text-slate-400">{copy.front}</p><p className="mt-2 whitespace-pre-wrap text-[#111943]">{card.frontText}</p>{card.readingText&&<div className="mt-2"><p className="font-semibold text-blue-700">{card.readingText}</p>{card.romanization&&<p className="text-sm text-slate-400">{card.romanization}</p>}</div>}{card.languageCode&&<div className="mt-3 flex justify-start"><PronunciationControls text={card.readingText??card.frontText} languageCode={card.languageCode}/></div>}</div><div><p className="text-xs font-bold text-slate-400">{copy.back}</p><p className="mt-2 whitespace-pre-wrap text-slate-700">{card.backText}</p>{card.explanation&&<p className="mt-3 text-sm italic text-slate-500">{card.explanation}</p>}{card.exampleText&&<div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm"><strong>{card.exampleText}</strong>{card.exampleTranslation&&<p className="mt-1 text-slate-500">{card.exampleTranslation}</p>}</div>}{card.memoryTip&&<p className="mt-2 text-sm text-amber-800">💡 {card.memoryTip}</p>}{card.enableReverseRecall&&<p className="mt-2 text-xs font-bold text-indigo-600">↔ {copy.reverse}</p>}</div><div className="flex gap-3 sm:flex-col"><button onClick={()=>setEditing(true)} className="text-sm font-bold text-blue-600">{copy.edit}</button><button onClick={onDelete} className="text-sm font-bold text-red-600">{copy.delete}</button></div></div>
    {card.imageUrl&&<FlashcardImage imageUrl={card.imageUrl} alt={card.frontText} className="mt-4 max-h-72 w-full rounded-xl bg-slate-50 object-contain"/>}<div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><label className="cursor-pointer rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">🖼 {card.imageUrl?copy.replaceImage:copy.image}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={event=>{const file=event.target.files?.[0];if(file)void onUploadImage(file);event.currentTarget.value='' }}/></label>{card.imageUrl&&<button disabled={pending} onClick={()=>void onDeleteImage()} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-600">{copy.removeImage}</button>}<button disabled={aiPending} onClick={()=>explain.mutate()} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">✨ {copy.explain}</button><button disabled={aiPending} onClick={()=>similar.mutate()} className="rounded-lg bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700">↗ {copy.similar}</button><SourceViewer target={{type:'flashcard',id:card.id}} compact/></div>{aiPending&&<p className="mt-3 text-sm text-slate-500">{copy.working}</p>}{aiError&&<p className="mt-3 text-sm text-red-700">{aiError.message}</p>}{aiResult&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700"><p>{aiResult.text}</p><div className="mt-3"><SourceViewer target={{type:'job',id:aiResult.jobId}} sources={aiResult.sources} compact/></div></div>}
  </article>
}
