import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { studySetKeys, studySetsApi } from '@/features/studySets/api/studySetsApi'
import { useLanguage } from '@/i18n/LanguageProvider'

export function CombineStudySetsPage(){
  const {id=''}=useParams();const location=useLocation();const edit=location.state as {reviewSetId:string;title:string;sourceIds:string[]}|null;const {language}=useLanguage();const vi=language==='vi';const navigate=useNavigate();const queryClient=useQueryClient();const [selected,setSelected]=useState<string[]>(edit?.sourceIds??[]);const [title,setTitle]=useState(edit?.title??'');const sets=useQuery({queryKey:studySetKeys.bySubject(id),queryFn:()=>studySetsApi.list(id),enabled:Boolean(id)});const create=useMutation({mutationFn:()=>edit?studySetsApi.updateSources(edit.reviewSetId,selected):studySetsApi.createCombined(id,{title:title.trim(),description:null,sourceStudySetIds:selected}),onSuccess:async value=>{await queryClient.invalidateQueries({queryKey:studySetKeys.bySubject(id)});navigate(`/study-sets/${value.id}`)}})
  const copy=vi?{back:'Về môn học',title:'Tạo bộ ôn tập',help:'Bộ ôn tập chỉ tham chiếu đến các bộ nguồn. Mọi chỉnh sửa và tiến độ luôn dùng flashcard gốc.',name:'Tên bộ ôn tập',cards:'thẻ',selected:'đã chọn',study:'Học cùng nhau ngay',save:'Lưu bộ ôn tập',loading:'Đang tải…',need:'Cần chọn ít nhất 2 bộ học tiêu chuẩn.'}:{back:'Back to subject',title:'Create review set',help:'A review set only references its sources. Edits and progress always use the original flashcards.',name:'Review set name',cards:'cards',selected:'selected',study:'Study together now',save:'Save review set',loading:'Loading…',need:'Choose at least 2 standard study sets.'}
  if(sets.isPending)return <main className="grid min-h-screen place-items-center text-slate-500">{copy.loading}</main>;const standard=sets.data?.filter(x=>x.type==='Standard')??[];const total=standard.filter(x=>selected.includes(x.id)).reduce((sum,x)=>sum+x.totalCards,0);const toggle=(setId:string)=>setSelected(value=>value.includes(setId)?value.filter(x=>x!==setId):[...value,setId])
  return <main className="mx-auto min-h-screen max-w-3xl px-5 py-10"><Link to={`/subjects/${id}`} className="text-sm font-bold text-indigo-600">← {copy.back}</Link><section className="sf-card mt-6 rounded-[2rem] p-6 sm:p-9"><h1 className="text-3xl font-bold text-[#111943]">{copy.title}</h1><p className="mt-3 leading-7 text-slate-500">{copy.help}</p><div className="mt-7 space-y-3">{standard.map(set=><label key={set.id} className={`flex cursor-pointer items-center gap-4 rounded-xl border p-4 ${selected.includes(set.id)?'border-indigo-500 bg-indigo-50':'border-slate-200'}`}><input type="checkbox" checked={selected.includes(set.id)} onChange={()=>toggle(set.id)} className="h-5 w-5"/><span className="flex-1"><strong className="block text-[#111943]">{set.title}</strong><span className="text-sm text-slate-500">{set.totalCards} {copy.cards}</span></span></label>)}</div><p className="mt-4 text-sm font-bold text-indigo-700">{selected.length} {copy.selected} · {total} {copy.cards}</p>{selected.length<2&&<p className="mt-2 text-sm text-amber-700">{copy.need}</p>}<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={150} placeholder={copy.name} className="mt-5 w-full rounded-xl border border-slate-300 p-3"/><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={selected.length<2} onClick={()=>navigate(`/study-together?sets=${selected.join(',')}`)} className="rounded-xl border border-indigo-300 px-5 py-3 font-bold text-indigo-700 disabled:opacity-40">{copy.study}</button><button disabled={selected.length<2||!title.trim()||create.isPending} onClick={()=>create.mutate()} className="sf-primary rounded-xl px-5 py-3 font-bold text-white disabled:opacity-40">{copy.save}</button></div>{create.isError&&<p className="mt-3 text-sm text-red-600">{create.error.message}</p>}</section></main>
}
