import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import { studySetsApi } from '@/features/studySets/api/studySetsApi'
import { reviewsApi } from '@/features/progress/api/reviewsApi'
import { RatingButtons } from '@/features/progress/components/RatingButtons'
import { FlashcardImage } from '@/features/flashcards/components/FlashcardImage'
import { PronunciationControls } from '@/features/flashcards/components/PronunciationControls'
import type { ReviewRating } from '@/features/progress/types/progress'
import { useLanguage } from '@/i18n/LanguageProvider'
import { LearningSessionShell, SessionHeader, SessionProgress, SessionSummary } from '@/features/learning/components/LearningSessionShell'

export function StudyTogetherPage(){
  const [params]=useSearchParams();const ids=(params.get('sets')??'').split(',').filter(Boolean);const {language}=useLanguage();const vi=language==='vi';const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const plan=useQuery({queryKey:['study-together',...ids],queryFn:()=>studySetsApi.studyTogether(ids),enabled:ids.length>=2});const card=plan.data?.flashcards[index];const rate=useMutation({mutationFn:(rating:ReviewRating)=>reviewsApi.review(card!.id,rating,undefined,'StudyTogether'),onSuccess:()=>{setIndex(value=>value+1);setRevealed(false)}});const copy=vi?{exit:'Thoát',title:'Học cùng nhau',answer:'Đáp án',question:'Câu hỏi',reveal:'Hiện đáp án',empty:'Không có flashcard trong các bộ đã chọn.',done:'Đã hoàn thành phiên học',home:'Về trang chủ'}:{exit:'Exit',title:'Study together',answer:'Answer',question:'Question',reveal:'Reveal answer',empty:'The selected sets have no flashcards.',done:'Study session complete',home:'Back home'}
  if(plan.isPending)return <main className="grid min-h-screen place-items-center text-slate-500" aria-live="polite">{vi?'Đang chuẩn bị…':'Preparing…'}</main>;if(plan.isError)return <main className="grid min-h-screen place-items-center text-red-600">{vi?'Không thể bắt đầu phiên học. Hãy thử lại.':'This study session could not be started. Try again.'}</main>;if(!plan.data?.flashcards.length)return <main className="grid min-h-screen place-items-center"><div className="text-center"><p>{copy.empty}</p><Link to="/home" className="mt-4 block text-blue-600">{copy.home}</Link></div></main>;if(!card)return <SessionSummary eyebrow={copy.done} title={`${plan.data.flashcards.length} ${vi?'thẻ đã học':'cards studied'}`} primaryAction={<Link to="/home" className="sf-primary rounded-xl px-5 py-3 font-bold text-white">{copy.home}</Link>}/>
  const source=plan.data.sources.find(x=>x.id===card.studySetId)
  return <LearningSessionShell><SessionHeader exitLabel={copy.exit} exitTo="/home" current={index+1} total={plan.data.flashcards.length}/><div className="mt-4"><SessionProgress current={index+1} total={plan.data.flashcards.length}/></div><p className="mt-6 text-xs font-bold uppercase tracking-wider text-indigo-600">{copy.title} · {source?.title}</p>{card.imageUrl&&!revealed&&<FlashcardImage imageUrl={card.imageUrl} alt={card.frontText} className="mt-5 max-h-60 w-full rounded-2xl bg-white object-contain p-2"/>}<section className="sf-card mt-5 flex min-h-80 flex-col items-center justify-center rounded-[2rem] p-8 text-center"><span className={`rounded-full px-3 py-1 text-xs font-bold ${revealed?'bg-emerald-100 text-emerald-700':'bg-blue-100 text-blue-700'}`}>{revealed?copy.answer:copy.question}</span><h1 className="mt-7 whitespace-pre-wrap text-3xl font-bold text-[#111943]">{revealed?card.backText:card.frontText}</h1>{!revealed&&card.languageCode&&<div className="mt-5"><PronunciationControls text={card.readingText||card.frontText} languageCode={card.languageCode}/></div>}{revealed&&card.explanation&&<p className="mt-6 text-slate-500">{card.explanation}</p>}</section><div className="mt-5">{revealed?<RatingButtons pending={rate.isPending} onRate={rating=>rate.mutate(rating)}/>:<button onClick={()=>setRevealed(true)} className="sf-primary w-full rounded-xl py-3 font-bold text-white">{copy.reveal}</button>}</div></LearningSessionShell>
}
