import { useRef, useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { LanguageSwitch } from '@/components/AppShell'
import { dailyStudyApi } from '@/features/dailyStudy/api/dailyStudyApi'
import type { DailyStudyFocus, DailyStudyItem, DailyStudyPlan } from '@/features/dailyStudy/types/dailyStudy'
import { evaluateAnswer, type AnswerEvaluation } from '@/features/dailyStudy/utils/answerEvaluation'
import { PronunciationControls } from '@/features/flashcards/components/PronunciationControls'
import { RatingButtons } from '@/features/progress/components/RatingButtons'
import { reviewKeys, reviewsApi } from '@/features/progress/api/reviewsApi'
import type { ReviewRating } from '@/features/progress/types/progress'
import { studySessionsApi } from '@/features/studySessions/api/studySessionsApi'
import { useLanguage } from '@/i18n/LanguageProvider'
import { FlashcardImage } from '@/features/flashcards/components/FlashcardImage'
import { LearningSessionShell, SessionHeader, SessionProgress, SessionSummary } from '@/features/learning/components/LearningSessionShell'

export function DailyStudyPage() {
  const { language } = useLanguage(); const vi = language === 'vi'; const navigate = useNavigate(); const queryClient = useQueryClient()
  const [minutes, setMinutes] = useState(15); const [focus, setFocus] = useState<DailyStudyFocus>('Balanced'); const [plan, setPlan] = useState<DailyStudyPlan | null>(null); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [evaluation, setEvaluation] = useState<AnswerEvaluation | null>(null); const [completed, setCompleted] = useState(0)
  const activeSession = useRef<{id:string;studySetId:string}|null>(null)
  const copy = vi ? { title:'Học hôm nay', subtitle:'StudyFlow tự chọn nội dung quan trọng nhất để bạn không phải mất thời gian quyết định.', duration:'Thời lượng', balanced:'Cân bằng', written:'Tự nhập đáp án', language:'Ngoại ngữ', start:'Bắt đầu học', preparing:'Đang chuẩn bị…', empty:'Chưa có thẻ phù hợp', emptyHelp:'Hãy thêm flashcard hoặc chọn một chế độ khác.', home:'Về trang chủ', exit:'Thoát', listen:'Nghe và nhập nghĩa', reverse:'Nhìn nghĩa và nhập từ', recall:'Tự nhớ và nhập đáp án', placeholder:'Nhập câu trả lời từ trí nhớ…', check:'Kiểm tra', correct:'Chính xác', close:'Gần đúng', incorrect:'Cần học thêm', expected:'Đáp án chuẩn', yours:'Bạn trả lời', example:'Ví dụ', memory:'Mẹo nhớ', complete:'Hoàn thành buổi học', done:'Bạn đã hoàn thành phiên học hôm nay.', again:'Hãy tự đánh giá để lên lịch ôn phù hợp.' } : { title:'Study today', subtitle:'StudyFlow selects the most useful material so you can start without deciding what to study.', duration:'Duration', balanced:'Balanced', written:'Written answers', language:'Language practice', start:'Start studying', preparing:'Preparing…', empty:'No matching cards', emptyHelp:'Add flashcards or choose another mode.', home:'Back home', exit:'Exit', listen:'Listen and type the meaning', reverse:'See the meaning and type the word', recall:'Recall and type the answer', placeholder:'Type your answer from memory…', check:'Check answer', correct:'Correct', close:'Almost correct', incorrect:'Needs work', expected:'Expected answer', yours:'Your answer', example:'Example', memory:'Memory tip', complete:'Session complete', done:'You completed today’s study session.', again:'Rate your recall to schedule the next review.' }
  const start = useMutation({ mutationFn:()=>dailyStudyApi.getPlan(minutes,focus), onSuccess:value=>{setPlan(value);setIndex(0)} })
  const rate = useMutation({ mutationFn:async({item,rating}:{item:DailyStudyItem;rating:ReviewRating})=>{if(activeSession.current?.studySetId!==item.studySetId){if(activeSession.current)await studySessionsApi.complete(activeSession.current.id);activeSession.current={id:(await studySessionsApi.start(item.studySetId,'DailyStudy')).id,studySetId:item.studySetId}}return reviewsApi.review(item.flashcardId,rating,activeSession.current.id,'DailyStudy',{submittedAnswer:answer,attemptType:'Recall',direction:item.activity==='ReverseWritten'?'Reverse':'Forward',clientAttemptId:crypto.randomUUID()})},onSuccess:async()=>{setCompleted(value=>value+1);setAnswer('');setEvaluation(null);if(plan&&index+1>=plan.items.length){if(activeSession.current)await studySessionsApi.complete(activeSession.current.id);activeSession.current=null;queryClient.invalidateQueries({queryKey:reviewKeys.due});queryClient.invalidateQueries({queryKey:['dashboard']})}setIndex(value=>value+1)}})
  async function exit(){if(activeSession.current)await studySessionsApi.complete(activeSession.current.id);navigate('/home')}
  if(!plan)return <main className="grid min-h-screen place-items-center px-5"><div className="absolute right-5 top-5"><LanguageSwitch/></div><section className="sf-card w-full max-w-xl rounded-[2rem] p-7 sm:p-9"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-100 text-3xl">◎</span><h1 className="mt-5 text-4xl font-bold tracking-tight text-[#111943]">{copy.title}</h1><p className="mt-3 leading-7 text-slate-500">{copy.subtitle}</p><p className="mt-7 text-sm font-bold text-slate-700">{copy.duration}</p><div className="mt-3 grid grid-cols-4 gap-2">{[5,10,15,0].map(value=><button key={value} onClick={()=>setMinutes(value)} className={`rounded-xl py-3 text-sm font-bold ${minutes===value?'bg-blue-600 text-white':'bg-slate-100 text-slate-600'}`}>{value||'∞'}{value?' min':''}</button>)}</div><div className="mt-6 grid gap-2 sm:grid-cols-3">{([['Balanced',copy.balanced],['Written',copy.written],['Language',copy.language]] as const).map(([value,label])=><button key={value} onClick={()=>setFocus(value)} className={`rounded-xl border p-4 text-sm font-bold ${focus===value?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200 text-slate-600'}`}>{label}</button>)}</div><button disabled={start.isPending} onClick={()=>start.mutate()} className="sf-primary mt-7 w-full rounded-xl py-3.5 font-bold text-white">{start.isPending?copy.preparing:copy.start}</button>{start.isError&&<p className="mt-3 text-sm text-red-600">{start.error.message}</p>}<Link to="/home" className="mt-5 block text-center text-sm text-slate-500">{copy.home}</Link></section></main>
  if(!plan.items.length)return <main className="grid min-h-screen place-items-center px-5 text-center"><section className="sf-card max-w-md rounded-[2rem] p-9"><h1 className="text-2xl font-bold">{copy.empty}</h1><p className="mt-3 text-slate-500">{copy.emptyHelp}</p><button onClick={()=>setPlan(null)} className="mt-6 font-bold text-blue-600">← {copy.home}</button></section></main>
  if(index>=plan.items.length)return <SessionSummary eyebrow={copy.complete} title={`${completed}/${plan.items.length}`} description={copy.done} metrics={[{label:vi?'Đã hoàn thành':'Completed',value:completed},{label:vi?'Tổng hoạt động':'Total activities',value:plan.items.length}]} primaryAction={<Link to="/home" className="sf-primary rounded-xl py-3 font-bold text-white">{copy.home}</Link>}/>
  const item=plan.items[index];const reverse=item.activity==='ReverseWritten';const listening=item.activity==='Listening';const expected=reverse?item.frontText:item.backText;const alternatives=reverse?[item.readingText,item.romanization]:[item.acceptedAnswers]
  function check(){setEvaluation(evaluateAnswer(answer,expected,alternatives))}
  const activityLabel=listening?copy.listen:reverse?copy.reverse:copy.recall
  return <LearningSessionShell><SessionHeader exitLabel={copy.exit} onExit={()=>void exit()} current={index+1} total={plan.items.length}/><div className="mt-4"><SessionProgress current={index+1} total={plan.items.length}/></div><div className="mt-6"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">{activityLabel}</p><h1 className="mt-1 font-bold text-[#111943]">{item.studySetTitle}</h1></div>{item.imageUrl&&<FlashcardImage imageUrl={item.imageUrl} alt={item.frontText} className="mt-5 max-h-60 w-full rounded-2xl bg-white object-contain p-2 shadow-sm"/>}
    <section className="sf-card mt-5 rounded-[2rem] p-6 sm:p-9"><div className="flex items-center justify-between"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{item.reason}</span><span className="text-xs font-semibold text-slate-400">{activityLabel}</span></div>{listening?<div className="mt-10 flex flex-col items-center"><span className="text-5xl">🎧</span>{item.languageCode&&<div className="mt-5"><PronunciationControls text={item.readingText||item.frontText} languageCode={item.languageCode}/></div>}</div>:<h2 className="mt-8 whitespace-pre-wrap text-center text-3xl font-bold leading-10 text-[#111943]">{reverse?item.backText:item.frontText}</h2>}
      {!evaluation?<><textarea autoFocus value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();if(answer.trim())check()}}} rows={3} placeholder={copy.placeholder} className="mt-9 w-full rounded-xl border border-slate-300 p-4 text-lg outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/><button disabled={!answer.trim()} onClick={check} className="sf-primary mt-4 w-full rounded-xl py-3 font-bold text-white disabled:opacity-40">{copy.check}</button></>:<div className="mt-8"><div className={`rounded-xl p-5 ${evaluation.result==='correct'?'bg-emerald-50 text-emerald-800':evaluation.result==='close'?'bg-amber-50 text-amber-900':'bg-red-50 text-red-800'}`}><p className="font-bold">{evaluation.result==='correct'?`✓ ${copy.correct}`:evaluation.result==='close'?`≈ ${copy.close}`:`✕ ${copy.incorrect}`}</p><p className="mt-3 text-xs font-bold uppercase opacity-60">{copy.yours}</p><p className="mt-1">{answer}</p><p className="mt-3 text-xs font-bold uppercase opacity-60">{copy.expected}</p><p className="mt-1 text-lg font-semibold">{expected}</p>{item.readingText&&<p className="mt-2">{item.readingText}{item.romanization?` · ${item.romanization}`:''}</p>}</div>{item.exampleText&&<div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold text-blue-500">{copy.example}</p><p className="mt-2 font-semibold text-blue-950">{item.exampleText}</p>{item.exampleTranslation&&<p className="mt-1 text-sm text-blue-700">{item.exampleTranslation}</p>}</div>}{item.memoryTip&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">💡 <strong>{copy.memory}:</strong> {item.memoryTip}</p>}{item.explanation&&<p className="mt-4 text-sm leading-6 text-slate-500">{item.explanation}</p>}<p className="mt-6 text-center text-xs text-slate-400">{copy.again}</p><div className="mt-3"><RatingButtons pending={rate.isPending} onRate={rating=>rate.mutate({item,rating})}/></div>{rate.isError&&<p className="mt-3 text-center text-sm text-red-600">{rate.error.message}</p>}</div>}
    </section></LearningSessionShell>
}
