import { useEffect, useEffectEvent, useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { quizzesApi } from '@/features/quizzes/api/quizzesApi'
import type { QuizResult, QuizSession } from '@/features/quizzes/types/quiz'
import { LanguageSwitch } from '@/components/AppShell'
import { useLanguage } from '@/i18n/LanguageProvider'
import { SourceViewer } from '@/features/grounding/components/SourceViewer'
import { LearningSessionShell, SessionHeader, SessionProgress } from '@/features/learning/components/LearningSessionShell'

export function QuizPage() {
  const { id = '' } = useParams(); const { language, t } = useLanguage(); const vi = language === 'vi'
  const [session, setSession] = useState<QuizSession | null>(null); const [result, setResult] = useState<QuizResult | null>(null); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<Record<string, string>>({})
  const copy = vi ? { label: 'StudyFlow trắc nghiệm', ready: 'Sẵn sàng kiểm tra trí nhớ?', intro: 'Bạn có thể đổi đáp án trước khi nộp. Đáp án đúng chỉ hiện sau khi chấm.', preparing: 'Đang chuẩn bị…', unable: 'Không thể bắt đầu bài trắc nghiệm.', trueFalse: 'Đúng hoặc sai', multiple: 'Chọn một đáp án', next: 'Tiếp theo', previous: 'Trước', unanswered: 'Hãy trả lời tất cả câu hỏi trước khi nộp.', shortcut: 'Nhấn phím 1–4 để chọn nhanh đáp án.' } : { label: 'StudyFlow quiz', ready: 'Ready to test your recall?', intro: 'You can change answers before submitting. Correct answers stay hidden until grading.', preparing: 'Preparing…', unable: 'Unable to start this quiz.', trueFalse: 'True or false', multiple: 'Choose one answer', next: 'Next', previous: 'Previous', unanswered: 'Answer every question before submitting.', shortcut: 'Press 1–4 to select an answer quickly.' }
  const start = useMutation({ mutationFn: () => quizzesApi.start(id), onSuccess: (value) => { setSession(value); setIndex(0); setSelected({}) } })
  const answer = useMutation({ mutationFn: ({ questionId, optionId }: { questionId: string; optionId: string }) => quizzesApi.answer(session!.attemptId, questionId, optionId), onSuccess: (_, input) => setSelected((current) => ({ ...current, [input.questionId]: input.optionId })) })
  const complete = useMutation({ mutationFn: () => quizzesApi.complete(session!.attemptId), onSuccess: setResult })
  const question = session?.questions[index]
  const chooseFromKeyboard = useEffectEvent((questionId: string, optionId: string) => answer.mutate({ questionId, optionId }))
  useEffect(() => { function keydown(event: KeyboardEvent) { if (!question || answer.isPending) return; const optionIndex = Number(event.key) - 1; if (optionIndex >= 0 && question.options[optionIndex]) chooseFromKeyboard(question.id, question.options[optionIndex].id); if (event.key === 'ArrowLeft') setIndex((value) => Math.max(0, value - 1)); if (event.key === 'ArrowRight' && session) setIndex((value) => Math.min(session.questions.length - 1, value + 1)) } window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown) }, [question, answer.isPending, session])
  if (result) return <QuizResults result={result} />
  if (!session) return <main className="grid min-h-screen place-items-center px-6"><div className="absolute right-6 top-6"><LanguageSwitch /></div><div className="max-w-md text-center"><p className="text-sm font-semibold text-indigo-600">{copy.label}</p><h1 className="mt-3 text-3xl font-semibold text-slate-950">{copy.ready}</h1><p className="mt-3 leading-7 text-slate-500">{copy.intro}</p><button disabled={start.isPending} onClick={() => start.mutate()} className="mt-8 rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white">{start.isPending ? copy.preparing : t('startQuiz')}</button>{start.isError && <p className="mt-4 text-sm text-red-600">{copy.unable}</p>}<div><Link to="/subjects" className="mt-6 inline-block text-sm text-slate-500">{t('backLibrary')}</Link></div></div></main>
  const answeredCount = Object.keys(selected).length
  return <LearningSessionShell width="max-w-4xl">
    <SessionHeader exitLabel={t('backLibrary')} exitTo="/subjects" current={index+1} total={session.questions.length}/>
    <div className="mt-6 flex items-center justify-between"><span className="truncate font-semibold text-slate-700">{session.title}</span><span className="metric-number text-sm text-slate-500">{index + 1} / {session.questions.length}</span></div>
    <div className="mt-4"><SessionProgress current={index+1} total={session.questions.length}/></div><nav className="mt-4 flex gap-2 overflow-x-auto pb-2" aria-label={t('question')}>{session.questions.map((item, position) => <button key={item.id} onClick={() => setIndex(position)} className={`h-10 w-10 shrink-0 rounded-lg text-sm font-bold ${position === index ? 'bg-blue-600 text-white' : selected[item.id] ? 'bg-emerald-100 text-emerald-700' : 'bg-white text-slate-500'}`}>{position + 1}</button>)}</nav>
    <section className="sf-card mt-5 rounded-[2rem] p-6 sm:p-9"><p className="text-xs font-semibold text-indigo-600">{question!.type === 'TrueFalse' ? copy.trueFalse : copy.multiple}</p><h1 className="mt-4 whitespace-pre-wrap text-2xl font-semibold leading-9 text-slate-950">{question!.questionText}</h1><div className="mt-8 space-y-3">{question!.options.map((option, optionIndex) => <button key={option.id} disabled={answer.isPending} onClick={() => answer.mutate({ questionId: question!.id, optionId: option.id })} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition active:scale-[.99] ${selected[question!.id] === option.id ? 'border-indigo-500 bg-indigo-50 text-indigo-800' : 'border-slate-200 bg-white hover:border-indigo-300'}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-sm font-bold">{optionIndex + 1}</span><span>{option.text}</span></button>)}</div><p className="mt-5 text-xs text-slate-400">{copy.shortcut}</p></section>
    <div className="mt-6 flex justify-between gap-3"><button disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold disabled:opacity-40">← {copy.previous}</button>{index < session.questions.length - 1 ? <button onClick={() => setIndex((value) => value + 1)} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">{copy.next} →</button> : <button disabled={complete.isPending || answeredCount !== session.questions.length} onClick={() => complete.mutate()} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white disabled:opacity-40">{t('submitQuiz')}</button>}</div>
    <p className="mt-4 text-center text-sm text-slate-400">{answeredCount}/{session.questions.length} {t('answered')}</p>{index === session.questions.length - 1 && answeredCount !== session.questions.length && <p className="mt-2 text-center text-sm text-amber-700">{copy.unanswered}</p>}
  </LearningSessionShell>
}

function QuizResults({ result }: { result: QuizResult }) {
  const { t } = useLanguage(); const wrong = result.questions.filter((question) => !question.isCorrect)
  return <LearningSessionShell width="max-w-4xl"><section className="rounded-3xl bg-white p-7 shadow-[0_16px_44px_rgba(38,56,112,.08)] sm:p-8"><p className="text-sm font-semibold text-indigo-600">{t('quizComplete')}</p><h1 className="metric-number mt-3 text-5xl font-semibold text-slate-950">{result.score}%</h1><p className="mt-3 text-slate-500">{result.correctCount} {t('correct')} · {result.wrongCount} {t('wrong')}</p></section><section className="mt-10"><h2 className="text-2xl font-semibold text-slate-950">{t('wrongReview')}</h2>{wrong.length === 0 ? <p className="mt-5 rounded-2xl bg-emerald-50 p-6 text-emerald-800">{t('allCaught')}</p> : <div className="mt-5 space-y-4">{wrong.map((item) => <article key={item.questionId} className="rounded-2xl bg-white p-6 shadow-[0_8px_28px_rgba(38,56,112,.06)]"><h3 className="font-semibold text-slate-950">{item.questionText}</h3><p className="mt-3 text-sm text-red-700">{t('yourAnswer')}: {item.selectedAnswer ?? t('noAnswer')}</p><p className="mt-1 text-sm text-emerald-700">{t('correctAnswer')}: {item.correctAnswer}</p>{item.explanation && <p className="mt-4 border-t border-slate-100 pt-4 text-sm text-slate-500">{item.explanation}</p>}<div className="mt-4"><SourceViewer target={{type:'question',id:item.questionId}} compact/></div></article>)}</div>}</section><Link to="/subjects" className="sf-primary mt-8 inline-flex min-h-11 items-center rounded-xl px-5 py-3 font-semibold text-white">{t('backLibrary')}</Link></LearningSessionShell>
}
